[project]
name = "character-identify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "logitec1994", email = "123654978a@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dbus-next>=0.2.3",
    "insightface>=2.0",
    "mediapipe>=1.0.1",
    "mss>=10.2.0",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "supervision>=0.30.5",
    "trackers>=2.6.1",
]

[project.scripts]
character-identify = "character_identify.main:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
