[project]
name = "character-identify"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "logitec1994", email = "123654978a@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
]

[project.scripts]
character-identify = "character_identify.main:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
